import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geoformHeavy = localFont({
  src: "./fonts/Geoform-Heavy.otf", // ✅ Updated path
  weight: "900",
  variable: "--font-geoform-heavy",
});

const geoformItalic = localFont({
  src: "./fonts/Geoform-MediumItalic.ttf", // ✅ Updated path
  weight: "500",
  style: "italic",
  variable: "--font-geoform-italic",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geoformHeavy.variable} ${geoformItalic.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
